# Generated by Django 4.0.5 on 2022-07-04 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_featured_remove_product_summary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='D:\\Programming\\Python\\ecomiInternshala\\assets\\unavailable-image.jpg', upload_to='D:\\Programming\\Python\\ecomiInternshala\\assets'),
        ),
    ]
