# Generated by Django 4.0.5 on 2022-07-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='assets/unavailable-image.jpg', upload_to='assets/'),
        ),
    ]
